---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-nginx
  namespace: argocdApp
spec:
  project: default
  source:
    repoURL: https://github.com/samuraixheart/argoCD.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://kubernetes.default.svc